let games = [
   {
      image: 'https://icon-library.com/images/league-of-legend-icon/league-of-legend-icon-8.jpg',
      name: 'League of Legends',
      tag: 'Соревновательные Популярные',
      uri: 'LeagueofLegends',
   },
   {
      image: 'https://cdnb.artstation.com/p/assets/images/images/003/638/701/large/yusif-alomeri-dota-emoticons-icon-circle.jpg?1475880618',
      name: 'Dota 2',
      tag: 'Соревновательные Популярные',
      uri: 'Dota2',
   },
   {
      image: 'https://42m8ekmoad.a.trbcdn.net/wp-content/uploads/2021/07/Rezhim-horror-i-karty-dlya-nego-v-ks-go.jpg',
      name: 'Counter-Strike: Global Offensive',
      tag: 'Соревновательные Популярные',
      uri: 'CSGO',
   },
   {
      image: '',
      name: 'Minecraft',
      tag: 'Кооперативные Популярные',
      uri: 'Minecraft',
   },
   {
      image: '',
      name: 'Rust',
      tag: 'Кооперативные Популярные',
      uri: 'Rust',
   },
   {
      image: '',
      name: 'Fortnite',
      tag: 'Соревновательные Популярные',
      uri: 'Fortnite',
   },
   {
      image: '',
      name: 'Brawl Stars',
      tag: 'Соревновательные Популярные',
      uri: 'BrawlStars',
   },
   {
      image: '',
      name: 'Standoff 2',
      tag: 'Соревновательные Популярные',
      uri: 'Standoff2',
   },
   {
      image: '',
      name: 'Genshin Impact',
      tag: 'Популярные',
      uri: 'GenshinImpact',
   },
   {
      image: '',
      name: 'Roblox',
      tag: 'Популярные',
      uri: 'Roblox',
   },
   {
      image: '',
      name: 'Grand Theft Auto V',
      tag: 'Популярные',
      uri: 'GTAV',
   },
   {
      image: '',
      name: 'Terraria',
      tag: 'Онлайн Популярные',
      uri: 'Terraria',
   },
   {
      image: 'Logo Apex Legends',
      name: 'Apex Legends',
      tag: 'Соревновательные Популярные',
      uri: 'ApexLegends',
   },
   {
      image: 'Logo Valorant',
      name: 'Valorant',
      tag: 'Онлайн Популярные',
      uri: 'Valorant',
   },
   {
      image: 'Logo PUBG Mobile',
      name: 'PUBG Mobile',
      tag: 'Онлайн Популярные',
      uri: 'PUBGMobile',
   },
   {
      image: 'Logo Dead by Daylight',
      name: 'Dead by Daylight',
      tag: 'Онлайн Популярные',
      uri: 'DbD',
   },
   {
      image: "Logo Garry's Mod",
      name: "Garry's Mod",
      tag: 'Онлайн',
      uri: 'GarrysMod',
   },
   {
      image: 'Logo GTA: San Andreas Multiplayer',
      name: 'GTA: San Andreas Multiplayer',
      tag: 'Онлайн',
      uri: 'GTASAMP',
   },
   {
      image: "Logo Tom Clancy's Rainbow Six: Siege",
      name: "Tom Clancy's Rainbow Six: Siege",
      tag: 'Онлайн',
      uri: 'R6',
   },
   {
      image: 'Logo ARK: Survival Evolved',
      name: 'ARK: Survival Evolved',
      tag: 'Онлайн',
      uri: 'ARK',
   },
   {
      image: 'Logo DayZ',
      name: 'DayZ',
      tag: 'Онлайн',
      uri: 'DayZ',
   },
   {
      image: 'Logo Sea of Thieves',
      name: 'Sea of Thieves',
      tag: 'Онлайн',
      uri: 'SeaofThieves',
   },
   {
      image: 'Logo Call of Duty: Warzone',
      name: 'Call of Duty: Warzone',
      tag: 'Онлайн',
      uri: 'CoDWarzone',
   },
   {
      image: 'Logo Gartic Phone',
      name: 'Gartic Phone',
      tag: 'Онлайн',
      uri: 'GarticPhone',
   },
   {
      image: 'Logo Phasmophobia',
      name: 'Phasmophobia',
      tag: 'Онлайн',
      uri: 'Phasmophobia',
   },
   {
      image: 'Logo World of Tanks',
      name: 'World of Tanks',
      tag: 'Онлайн',
      uri: 'WoT',
   },
   {
      image: "Logo Don't Starve Together",
      name: "Don't Starve Together",
      tag: 'Онлайн',
      uri: 'DontStarve',
   },
   {
      image: 'Logo Rocket League',
      name: 'Rocket League',
      tag: 'Онлайн',
      uri: 'RocketLeague',
   },
   {
      image: 'Logo Escape from Tarkov',
      name: 'Escape from Tarkov',
      tag: 'Онлайн',
      uri: 'EscapefromTarkov',
   },
   {
      image: 'Logo Raft',
      name: 'Raft',
      tag: 'Онлайн',
      uri: 'Raft',
   },
   {
      image: 'Logo Unturned',
      name: 'Unturned',
      tag: 'Онлайн',
      uri: 'Unturned',
   },
   {
      image: 'Logo Warface',
      name: 'Warface',
      tag: 'Онлайн',
      uri: 'Warface',
   },
   {
      image: "Logo Playerunknown's Battlegrounds",
      name: "Playerunknown's Battlegrounds",
      tag: 'Онлайн',
      uri: 'PuBg',
   },
   {
      image: 'Logo Mobile Legends',
      name: 'Mobile Legends',
      tag: 'Онлайн',
      uri: 'MobileLegends',
   },
   {
      image: 'Logo The Forest',
      name: 'The Forest',
      tag: 'Онлайн',
      uri: 'TheForest',
   },
   {
      image: 'Logo Overwatch',
      name: 'Overwatch',
      tag: 'Онлайн',
      uri: 'Overwatch',
   },
   {
      image: 'Logo Counter-Strike',
      name: 'Counter-Strike',
      tag: 'Онлайн',
      uri: 'CounterStrike',
   },
   {
      image: 'Logo World of Tanks Blitz',
      name: 'World of Tanks Blitz',
      tag: 'Онлайн',
      uri: 'WoTBlitz',
   },
   {
      image: 'Logo Among Us',
      name: 'Among Us',
      tag: 'Онлайн',
      uri: 'AmongUs',
   },
   {
      image: 'Logo 7 Days to Die',
      name: '7 Days to Die',
      tag: 'Онлайн',
      uri: 'SevenDaystoDie',
   },
   {
      image: 'Logo Valheim',
      name: 'Valheim',
      tag: 'Онлайн',
      uri: 'Valheim',
   },
   {
      image: 'Logo Call of Duty: Mobile',
      name: 'Call of Duty: Mobile',
      tag: 'Онлайн',
      uri: 'CoDMobile',
   },
   {
      image: 'Logo Far Cry 5',
      name: 'Far Cry 5',
      tag: 'Онлайн',
      uri: 'FarCry5',
   },
   {
      image: 'Logo Scrap Mechanic',
      name: 'Scrap Mechanic',
      tag: 'Онлайн',
      uri: 'ScrapMechanic',
   },
   {
      image: 'Logo Warframe',
      name: 'Warframe',
      tag: 'Онлайн',
      uri: 'Warframe',
   },
   {
      image: 'Logo Euro Truck Simulator 2',
      name: 'Euro Truck Simulator 2',
      tag: 'Онлайн',
      uri: 'EuroTruckSimulator2',
   },
   {
      image: 'Logo Paladins',
      name: 'Paladins',
      tag: 'Онлайн',
      uri: 'Paladins',
   },
   {
      image: 'Logo War Thunder',
      name: 'War Thunder',
      tag: 'Онлайн',
      uri: 'WarThunder',
   },
   {
      image: 'Logo World of Warcraft',
      name: 'World of Warcraft',
      tag: 'Онлайн',
      uri: 'WoW',
   },
   {
      image: 'Logo Dying Light',
      name: 'Dying Light',
      tag: 'Онлайн',
      uri: 'DyingLight',
   },
   {
      image: 'Logo Forza Horizon 4',
      name: 'Forza Horizon 4',
      tag: 'Онлайн',
      uri: 'ForzaHorizon4',
   },
   {
      image: 'Logo Payday 2',
      name: 'Payday 2',
      tag: 'Онлайн',
      uri: 'Payday2',
   },
   {
      image: 'Logo Hearts of Iron IV',
      name: 'Hearts of Iron IV',
      tag: 'Онлайн',
      uri: 'HoIIV',
   },
   {
      image: 'Logo Farming Simulator 19',
      name: 'Farming Simulator 19',
      tag: 'Онлайн',
      uri: 'FarmingSimulator19',
   },
   {
      image: 'Logo Albion Online',
      name: 'Albion Online',
      tag: 'Онлайн',
      uri: 'AlbionOnline',
   },
   {
      image: 'Logo Satisfactory',
      name: 'Satisfactory',
      tag: 'Онлайн',
      uri: 'Satisfactory',
   },
   {
      image: 'Logo Garena FreeFire: Wonderland',
      name: 'Garena Free Fire: Wonderland',
      tag: 'Онлайн',
      uri: 'GFFWonderland',
   },
   {
      image: 'Logo Portal 2',
      name: 'Portal 2',
      tag: 'Онлайн',
      uri: 'Portal2',
   },
   {
      image: 'Logo Red Dead Redemption 2',
      name: 'Red Dead Redemption 2',
      tag: 'Онлайн',
      uri: 'RDR2',
   },
   {
      image: 'Logo Geometry Dash',
      name: 'Geometry Dash',
      tag: 'Онлайн',
      uri: 'GeometryDash',
   },
   {
      image: 'Logo Project Zomboid',
      name: 'Project Zomboid',
      tag: 'Онлайн',
      uri: 'ProjectZomboid',
   },
   {
      image: 'Logo Battlefield 4',
      name: 'Battlefield 4',
      tag: 'Онлайн',
      uri: 'Battlefield4',
   },
   {
      image: 'Logo Battlefield V',
      name: 'Battlefield V',
      tag: 'Онлайн',
      uri: 'BattlefieldV',
   },
   {
      image: 'Logo Osu!',
      name: 'Osu!',
      tag: 'Онлайн',
      uri: 'Osu',
   },
   {
      image: 'Logo Clash of clans',
      name: 'Clash of clans',
      tag: 'Онлайн',
      uri: 'ClashofClans',
   },
   {
      image: 'Logo Muck',
      name: 'Muck',
      tag: 'Онлайн',
      uri: 'Muck',
   },
   {
      image: 'Logo Stardew Valley',
      name: 'Stardew Valley',
      tag: 'Онлайн',
      uri: 'StardewValley',
   },
   {
      image: 'Logo Arma 3',
      name: 'Arma 3',
      tag: 'Онлайн',
      uri: 'Arma3',
   },
   {
      image: 'Logo Crossout',
      name: 'Crossout',
      tag: 'Онлайн',
      uri: 'Crossout',
   },
   {
      image: 'Logo Deceit',
      name: 'Deceit',
      tag: 'Онлайн',
      uri: 'Deceit',
   },
   {
      image: 'Logo Grounded',
      name: 'Grounded',
      tag: 'Онлайн',
      uri: 'Grounded',
   },
   {
      image: 'Logo Stalcraft',
      name: 'Stalcraft',
      tag: 'Онлайн',
      uri: 'Stalcraft',
   },
   {
      image: 'Logo Borderlands 2',
      name: 'Borderlands 2',
      tag: 'Онлайн',
      uri: 'Borderlands2',
   },
];

export function getGames() {
   return games;
}
